apiVersion: v1
kind: Service
metadata:
  name: recsys-api-service
spec:
  selector:
    app: recsys-api
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 8000 # Port the container listens on
  # Use LoadBalancer for external access on cloud providers
  # Use ClusterIP for internal access
  type: LoadBalancer